### ISSUE TITLE
dir.friendica.com cronjob not working

### ISSUE THREAD

**Issue by Beanow** [friendica/dir#3]
When I compare the stats for dir.friendica.com with those on my experimental server, I can tell that the cronjob is not doing the maintenance jobs.

Possibly the cronjob is not configured yet, if not can you report an issue with any error logs?

**Comment by Beanow** [comment]
@friendica Does Red currently have job schedualing for shared host problems like this? If so, can you point me to related source code? Depending on how it looks we could package this as a seperate library usable for Red, Friendica and the Directory, with a collection of per-host recommended settings.

**Comment by friendica** [comment]
By default we turn all queue items into separate processes and run them one at a time separated by delivery_interval (which is in your site preferences). It's the same thing we did with the poller in Friendica. We had onepoll and onedeliver which handle one thing at a time. And we space these out by delivery_interval from the calling process. For Dreamhost I need to separate each process by 4-5 seconds to avoid having them killed for using too much resources. It only gives me about 10-15 concurrent processes before it starts killing things and I've got the friendica directory, a friendica node (that's mostly dormant but it's still handling traffic), four red servers and about fifteen other websites. Stuff gets killed all the time.   

Red adds the ability to batch 'n' jobs together into a single process, so we can do for instance 3-4 queue items per process, but I can't really use it. That allows sites with lots of resources to keep things pumping through as fast as they can handle.  

I would prefer to provide a DB dump of the directory and let somebody still working closely with the project take over the Friendica primary directory role (completely) so I can turn it off. I have no interest in making it scale or run on shared hosts. It's a global directory. It needs some decent resources, but the project was never able to provide these for me so I made do with what I had. It's grown since then and it's outgrown Dreamhost.

**Comment by Beanow** [comment]
I've started a seperate conversation about the hosting issues for dir.friendica.com specifically https://fc.oscp.info/display/140839323114383093854c23b75714cb

For the time being I would like to focus on the coding problem though. The current directory has multiple jobs. Scrapes, polls and syncing. So spacing out would only work if there is a generic task tracker. I'll have a look at the polling code see what I can take from this.

**Comment by MrPetovan** [comment]
Closed as stale.
